### ISSUE TITLE
Add nuxt eslint rules instead of "just standard"

### ISSUE THREAD

**Issue by manniL** [nuxt-contrib/opencollective#28]

**Comment by Patil2099** [comment]
@manniL Can I work on this. Also, Can you explain it a bit more?

**Comment by manniL** [comment]
@Patil2099 	Sure thing! :relaxed: 	

I'd like to have https://github.com/nuxt/eslint-config as (only) eslint config set. You can compare with other projects like https://github.com/Developmint/developmint.de/ how to set it up.

So the basic constraints are:

1. eslintrc(.js?) should only extend `@nuxtjs`
2. Lint errors should be fixed

Does that help?
