### ISSUE TITLE
0.3.2 isn't in npm

### ISSUE THREAD

**Issue by mikicho** [nuxt-contrib/opencollective#62]
0.3.2 fixes an important vulnerability by updating node-fetch to 2.6.1 but I can't find this version in npm:
https://www.npmjs.com/package/@nuxtjs/opencollective

Can you please publish this package to npm?
Thanks

**Comment by pi0** [comment]
Hi. Actually correct package is https://www.npmjs.com/package/@nuxt/opencollective

I will update `@nuxtjs` too and deprecate.
