### ISSUE TITLE
Upgrade node-fetch to fix vulnerability issue.

### ISSUE THREAD

**Issue by CarlMungazi** [nuxt-contrib/opencollective#72]
`node-fetch` has a vulnerability issue (https://github.com/advisories/GHSA-r683-j2x4-v87g) and the current package being used by opencollective uses the affected package. Any chance this dependency can be upgraded?

**Comment by simondean** [comment]
See https://github.com/node-fetch/node-fetch/issues/1467.  `package.json` just needs to be updated to `2.6.7` for `node-fetch`

**Comment by Spuuwn** [comment]
Can we get a fix for this please? The pull request was rejected. This is a major blocker for enterprise level project scanners picking this up as high/critical.
